#!/usr/bin/env ruby
ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
$:.unshift(File.join(ROOT, 'lib'))

# This totally counts as a test. Promise!

$reference ||= File.open("#{ROOT}/test/data/data.txt").read

def okay?(hiera)
  if hiera.lookup('data.txt', 'not found', {'root' => ROOT}) == $reference
    puts "Everything is ponies!"
  else
    puts "Everything is broken :("
    exit 1
  end
end

require 'hiera'
okay? Hiera.new(:config => "#{ROOT}/test/hiera-inline.yaml")
okay? Hiera.new(:config => "#{ROOT}/test/hiera-file.yaml")
